import localeDropdown from "./localeDropdown.js";
import setCurrentLocale from "./setCurrentLocale.js";
import mainSwiper from "./mainSwiper.js";
import navMenuMobileDropdown from "./navMenuMobileDropdown.js";
import currentYear from "./currentyear.js";
localeDropdown();
setCurrentLocale();
navMenuMobileDropdown();
mainSwiper();
currentYear();
